### ISSUE TITLE
Need canal inference

### ISSUE THREAD

**Issue by mauricewells** [AImageLab-zip/alveolar_canal#11]
There is no canal inference in this repo, so i can't test pre-trained checkpoint
How can I test pre-trained model from whole volume data

**Comment by prittt** [comment]
Dear @mauricewells, 

the inference code is available [here](https://github.com/AImageLab-zip/alveolar_canal/blob/190af1c7f17aa5625eccce722e2104497b2f7e69/experiments/generation.py#L39). This is the inference code for the generation phase, but if you will to perform the inference of 'standard' segmentation phase you can just copy and paste the same code in the Segmentation class, and remove the lines relative to the sparse annotations, specifically [this line](https://github.com/AImageLab-zip/alveolar_canal/blob/190af1c7f17aa5625eccce722e2104497b2f7e69/experiments/generation.py#L72) and [this line](https://github.com/AImageLab-zip/alveolar_canal/blob/190af1c7f17aa5625eccce722e2104497b2f7e69/experiments/generation.py#L76).
