### ISSUE TITLE
The length setting issue of 

### ISSUE THREAD

**Issue by lgh010319** [AImageLab-zip/alveolar_canal#13]
Hello author, I'm sorry to bother you. I would like to ask about the length of mem_1en. I saw that your code mem_1en=128. Is this setting related to each patch_sthape? What specifically refers to the length of a memory unit and what is stored in the memory unit? If my patch_sthape=(98, 98, 98), what should be the mem_1en set to

**Comment by LucaLumetti** [comment]
Hello,

The memory length is not restricted by the patch shape; it can be any value in $$[0, +\infty)$$, regardless of the patch shape you select. The memory consists of a set of `memory_length` tokens, which [are concatenated](https://github.com/AImageLab-zip/alveolar_canal/blob/51dbbc1cf34c65a434f4c39b91c144e7c48fc4d1/models/MemTransPosPadUNet3D.py#L43) with the tokens from the patch before being passed into the transformer module. These tokens are learned through the standard backpropagation algorithm and [are discarded afterward](https://github.com/AImageLab-zip/alveolar_canal/blob/51dbbc1cf34c65a434f4c39b91c144e7c48fc4d1/models/MemTransPosPadUNet3D.py#L53C9-L53C52).
The shape of a memory token is the same as the shape of a patch token, what exactly do they learn is really hard to tell but they should store some general representation that is then useful for the transformer.
If you didn't, I suggest you to read the [IEEE Access paper](https://iris.unimore.it/retrieve/e5959a29-6802-44e6-acfd-adb87c1eab0d/2024_ICPR_Location_Matters__Harnessing_Spatial_Information_to_Enhance_the_Segmentation_of_Inferior_Alveolar_Canal_in_CBCTs.pdf) and [the paper that proposed the Memory Transformer](https://arxiv.org/abs/2006.11527)

If you have any other questions or you need further explanation, do not hesitate to reach out again.

Luca
