### ISSUE TITLE
NaN error in validation phase

### ISSUE THREAD

**Issue by hvy1seok** [AImageLab-zip/alveolar_canal#7]
I am trying to run this code by using maxillo dataset. But it occurs a error below .

Traceback (most recent call last):
  File "/home/syu/Documents/maison/alveolar_canal/main.py", line 170, in <module>
    val_iou, val_dice = experiment.test(phase="Validation")
  File "/home/syu/Documents/maison/alveolar_canal/experiments/experiment.py", line 276, in test
    loss = self.loss(output.unsqueeze(0), gt.unsqueeze(0), partition_weights)
  File "/home/syu/Documents/maison/alveolar_canal/losses/LossFactory.py", line 60, in __call__
    raise ValueError(f'Loss {loss_name} has some NaN')
ValueError: Loss DiceLoss has some NaN

 I'm wondering if this code and dataset work as written on the readme or if there are no corrupted files in this dataset.
Big congratulation ti your acivements in cvpr!

**Comment by LucaLumetti** [comment]
Hi @hvy1seok,
I can assure you that there are no corrupted files, as long as they didn't get corrupted while you were downloading them, but it's quite unlikely. Looks like you used the DiceLoss, while we always employed the JaccardLoss. Thus, a bug might be slipped in the code of the DiceLoss and never get noticed, I'm gonna look deeply into it in the following days. if you would like to spend some time debugging it, I can give you some guess on which is the guilty part that produces NaNs:

- Assure that in this call, both `pred` and `gt` has no `NaNs`.
- Assure that also `gt_onehot` doesn't contain `NaNs`.
- Assure that `cardinality` has no zero values.
